### ISSUE TITLE
DI in Component

### ISSUE THREAD

**Issue by csharpdeveloper12** [zyanfx/Zyan#12]
Hello yallie,

is it possible to inject a property to a component automatically?

E.g.:
`public string Info { get; set; }`
While create the instance from the interface, the server inject in the property a pre-definied value.
Now the client can work with the property.
`MessageBox.Show(proxy.Info);`

Best regards and thanks in advance

csharpdeveloper12

**Comment by yallie** [comment]
Hello,

Not sure about your intentions here, but in short — no, that's not supported.
Zyan isn't a dependency container (also, not every IoC can do that with strings).
Perhaps if you outline your requirements, I can suggest an alternative.
In the meantime, I'd like to point out that `proxy.Info` is a remote call.
Are you sure you want a network round-trip just to read a string property?
That's a multitude times slower than reading an ordinary property,
i.e. tens to hundreds milliseconds vs a few nanoseconds.

**Comment by csharpdeveloper12** [comment]
Hello yallie,

thanks for your reply :)

The problem is: I need an option to notify global to a central component.
I have a component wich is allways created (Core) and multiple other components.
Now i want to notify from the other components the "Core". My idea was, that i create all members in "Core" (e.g. strings, events) and reference to this in the `SessionVariables`.
If a component want to notify the client, it can use the corresponding session variable and the core component notifies the client.

I hope my explanation is not too complicated ;)

**Comment by yallie** [comment]
Hello,

Suppose you have a central component used to notify all the clients. And you'd like your other server components route their events using that single central component. Is that what you're going to implement?

Assuming that you use Zyan+MEF integration on your server, my solution is as follows:

```c#
// core notification component interface
public interface ICoreNotifications 
{
	event EventHandler SomeEvent;
	event EventHandler AnotherEvent;
	...

	void RaiseSomeEvent(EventArgs e);
	void RaiseAnotherEvent(EventArgs e);
	...
}

// core notification component implementation, should be singleton (uses shared creation policy)
[ZyanComponent(typeof(ICoreNotifications)), CreationPolicy(PartCreationPolicy.Shared)]
public class CoreNotifications : ICoreNotifications
{
	public event EventHandler SomeEvent;

	public void RaiseSomeEvent(EventArgs e)
	{
		// Zyan will route this event to all connected clients
		SomeEvent?.Invoke(null, e);
	}
	...
} 

// non-core server component, can be either singleton or single-call
[ZyanComponent(typeof(ISomeComponent))]
public class SomeComponent : ISomeComponent
{
	// import core notification service to raise events
	[Import]
	private ICoreNotifications CoreNotifications { get; set; }

	// this method will notify all the clients using the core notification service
	public void DoSomethingCool()
	{
		// do some business logic
		...

		// notify all the clients
		CoreNotifications.RaiseSomeEvent(EventArgs.Empty);
	}
}
```

Does that make sense?

Regards, Alex

**Comment by csharpdeveloper12** [comment]
Hi Alex,

your supposition is nearly on my issue :)

The Core-Component is not for all clients rather only for the the actual session. Therefore my idea with the session variable.
My intention is, that i does not have to subscribe to every event in every component manually rather i subscribe the event in the core and all fired events for my session raises the core.
In the client i only subscribe the "Core-Event".

Tanks and best regards

**Comment by yallie** [comment]
To route your events to specific session, just inherit your EventArgs classes 
from SessionEventArgs so you don't need to deal with session variables manually:

```c#
[Serializable]
public class MyEventArgs : SessionEventArgs
{
     // add custom properties and methods
}
```
All events with SessionEventArgs-derived parameters will be routed to the same session
where they are created. It's very handy for miscellaneous tracing/debugging, such as
tracing all SQL queries invoked by your client's session. This special handling is already 
implemented for you, see the documentation for the [Session-bound events](http://zyan.codeplex.com/wikipage?title=Event%20filters&referringTitle=English%20Documentation).

Let me know if you need more examples and/or explanations :)

**Comment by csharpdeveloper12** [comment]
Hi Alex,

session-bound events ... Lose sight of the wood for the trees ... xD

I thank you so mutch once again :)
Thank you for your time for helping me and thank you for your offer:
> Let me know if you need more examples and/or explanations :)

Greetings and all the best :)

**Comment by yallie** [comment]
You're welcome! :)
