### ISSUE TITLE
Xamarin Forms and Serializable complex type

### ISSUE THREAD

**Issue by koo9** [zyanfx/Zyan#13]
with Xamarin.Forms, serializable attribute is not supported. what's the alternative for passing the complex type to/from a service?

**Comment by yallie** [comment]
Hello Kevin,

not sure what you mean about Xamarin Forms.

Xamarin Android itself supports Serializable (have a look at the [sample projects](https://github.com/zyanfx/Zyan/tree/master/examples/Zyan.Examples.Android)).
Xamarin Forms is just a library you add to your Xamarin application, so it doesn't
affect the features supported by the platform. Just make sure your application
is targeting full .NET framework, not .NET Core or PCL.

Regards, Alex

**Comment by koo9** [comment]
hi Alex,

Xamarin Android project is not PCL but Xamarin.Forms solution is PCL. so it does not have the full framework or even the slim down Mono framework.

**Comment by yallie** [comment]
Zyan requires full .NET Framework 3.5/4.5 (or Mono, or Xamarin.Android),
so it can't be added as a reference to a PCL-only solution, sorry.

But the opposite is possible, as far as I understand.

If Xamarin.Forms assemblies are PCL-only, you can reference them
from a full .NET 4.5 solution, as well as Zyan.Communication.dll.
So, to use Zyan, you need to re-target your solution to full .NET Framework profile.

PS. I had a MvvmCross client app running on Zyan server before Xamarin.Forms
were released, and PCL nature of MvvmCross libraries wasn't any obstable.
So I guess that's possible with Xamarin.Forms as well...

**Comment by koo9** [comment]
turns out the xamarin.forms shared project is not PCL. so can references zyan lib. 

Good work! Alex

**Comment by yallie** [comment]
Great!
Glad it helped

**Comment by koo9** [comment]
turns out xamarin.forms does not support remoting but since zyan reference the remoting dll. it won't work. guess I need to fall back to the xamarin native app.

**Comment by yallie** [comment]
I'm not sure I can understand you.
Are you talking about Xamarin Forms library or something like Xamarin Forms app template?

Xamarin Forms library itself is just a binary you can use in your application, so it has 
nothing to do with Remoting. To test if XF and Zyan can work together, try creating
a new .NET 4.5-based Xamarin Android application and adding both Nuget packages.
It should compile and run just fine.

If you're referring to the application template Xamarin Forms may come with, 
then perhaps yes, it may target a kind of .NET Framework that doesn't include Remoting.
If that's the case, then re-targeting your projects to the full .NET 4.5 should fix the issue.

**Comment by koo9** [comment]
you are right. the reason the xamarin form project was getting the remoting dll reference error is because I reference the service interface project directly instead of doing a file link. I created a forms project and able to get the duplex communication working.
