### ISSUE TITLE
No remote address specified for reconnect.

### ISSUE THREAD

**Issue by radio42** [zyanfx/Zyan#17]
Sometimes clients to report the following error/exception, which seems to happen unfrequently, but sometimes.

Do you know what might be causing this?
Many Thanks in advance...
Bernd

Error Message: No remote address specified for reconnect.
Error Type: System.Runtime.Remoting.RemotingException
Error Source: Zyan.Communication.Void CheckSocket()
********** System Stack Trace **********
à Zyan.Communication.Protocols.Tcp.DuplexChannel.Connection.CheckSocket()
à Zyan.Communication.Protocols.Tcp.DuplexChannel.Connection.get_Writer()
à Zyan.Communication.Protocols.Tcp.DuplexChannel.Message.Send(Connection connection, Guid guid, ITransportHeaders headers, Stream message)
à Zyan.Communication.Protocols.Tcp.DuplexChannel.ServerTransportSink.ReceiveMessage(IAsyncResult ar)
à Zyan.Communication.Protocols.Tcp.DuplexChannel.Manager.AsyncResult.DoCallback(Object o)
à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
à System.Threading.ThreadPoolWorkQueue.Dispatch()
à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by radio42** [comment]
Actually the issue started to happen once I changed my code according to our discussion in this ticket: #14

**Comment by yallie** [comment]
Hello,

>Sometimes clients to report the following error/exception, which seems to happen unfrequently, but sometimes.

1. Does your application clean up the delegates of the disconnected clients? Can you check it out using the debugger?
2. Or perhaps the issue happens when the server is being shut down? 

To me, it looks like the event is being fired on the connection that's already closed. Which IMO can happen due to one of these two reasons.

**Comment by radio42** [comment]
Hi,

to 1.:
I am not using events/delegates anymore, but the 'RegisterCallback' solution as we discussed in ticket #14 
I store these callback delegates in the 'SessionVariables' and retrieve them back on the server side using the unique session ID.
However, I do not explicitly delete or remove those callback delegates, as I assumed, that they are automatically cleaned up?!

to 2.:
No, it happens all of a sudden. And after that the communication seems to be broken.

**Comment by yallie** [comment]
>I am not using events/delegates anymore, but the 'RegisterCallback' solution as we discussed in ticket #14

RegisterCallback solution uses delegates under the hood.

>However, I do not explicitly delete or remove those callback delegates, as I assumed, that they are automatically cleaned up?!

SessionVariables — yes, they're cleaned up once the session is closed since version 2.8, if I'm not mistaken. But the exception you're seeing arises from a client's delegate using the closed connection, so I guess the delegate may be taken from elsewhere.

**Comment by yallie** [comment]
I looked at TcpExChannel code in Message.Send and saw that it expects various kinds of exceptions, such as ObjectDisposedException, SocketException, IOException, etc. — so it clearly assumes that the connection can be void at the moment of sending. But it doesn't handle the RemotingException, which looks like a bug to me.

I've fixed that, so please download the latest Zyan source code and build it yourself. Let me know if the fix works for you.

Cheers!

**Comment by radio42** [comment]
Great, many thanks!
I'll let you know, once I tested it, which might take a few days,, as I need to test that with a customer of mine which experienced the issue...(and I am not sure, if he is testing now over the weekend)!
Anyhow, many thanks for the great support!

**Comment by yallie** [comment]
You're welcome Bernd!

I'm closing the issue now, feel free to reopen and/or continue the discussion if needed.

Cheers!

**Comment by koo9** [comment]
looks like the nuget package is still at 2.8. anytime this fix will be updated for nuget?

**Comment by yallie** [comment]
Hello Kevin and Bernd,

Published the nuget: [Zyan v2.9](https://www.nuget.org/packages/Zyan)

Cheers, Alex

**Comment by koo9** [comment]
got it, thx!
