### ISSUE TITLE
Handle connection fault

### ISSUE THREAD

**Issue by koo9** [zyanfx/Zyan#19]
just wondering for a duplex connect, if the server crash, how is the client notified of such event? it seems like ZyanConnection.Error event won't fired when the server stop/failed.

**Comment by yallie** [comment]
Hello,

you're right, when the server crashes (or the network goes down), the connected socket may not get notified about the disconnect, so you won't get a socket exception until you try to send anything down the wire. So to detect the disconnect we can only rely on polling (aka heartbeats). I don't think it's properly documented, sorry. The only mention I've found is [at codeplex wiki](http://zyan.codeplex.com/wikipage?title=What%C2%B4s%20new%20in%20Zyan%202.0%3f):

### Disconnection detection

ZyanConnection.Disconnected event allows detecting unexpected disconnection.
Here is a short sample code snippet, how to use the feature:

```c#
var conn = new ZyanConnection(url);
conn.PollingEnabled = true;
conn.PollingInterval = TimeSpan.FromMinutes(1);
conn.Disconnected += (s, e) => 
    Console.WriteLine("Connection is lost! Exception details: " + e.Exception.Message);
```

There is also a possibility to make reconnection attempts. Set the Retry property of the DisconnectedEventArgs to true, if you want Zyan to retry. Retries are done as long as 
you set the Retry property inside your event handler to true.

For logging and troubleshooting purposes you can enable Polling Event Tracing on your 
host, to get notified when clients poll (sending heartbeat signals):

```c#
host.PollingEventTracingEnabled = true;
host.ClientHeartbeatReceived += (s, e) => 
    Console.WriteLine(string.Format("{0}: Heartbeat from client session '{1}' received.",
    e.HeartbeatReceiveTime, e.SessionID));
```

Here is the demo code for using these events:
https://gist.github.com/yallie/437ea4c087725693e1c2

UPD. Note that polling is not enabled by default. See also:
https://zyan.codeplex.com/discussions/573430

**Comment by koo9** [comment]
yes, I think that's how wcf handle connection fault issue and it's on by default.

Thanks for the example!

**Comment by yallie** [comment]
You're welcome!

**Comment by koo9** [comment]
hi Alex,

tried the pulling to detect server failure but it seems like the disconnected event does not fired after the pulling interval expires. it seems like there is a connection timeout there when doing a pull.

in wcf, the connection fault event fired almost instantly. there must be some differences in the implementation. 

anyways, I will look into the code to find out why.
