### ISSUE TITLE
Increasing threads/CPU usage

### ISSUE THREAD

**Issue by emlrsua** [zyanfx/Zyan#22]
I've been using Zyan.Communication.dll v2.8.0.0 with my C# code in Windows services on Windows Server 2012 and am pleased with it so far.

However, I've run into an issue when attempting to restore a Zyan connection, or create a new one, when a connection has been broken.  I notice that new threads are created that never die, even if I dispose of ZyanConnection objects.  This might also lead to increases in CPU usage.

Perhaps you can give me an idea of best practices, which hopefully will resolve the issue.  What I do now if there is a disconnection (for instance, by stopping a service) is to dispose of the ZyanConnection object and attempt to create a new one.  Here is a code snippet.

            if (_connection != null)
            {
                _connection.PollingEnabled = false;
                _connection.Dispose();
            }

            _connection = new ZyanConnection(ServerUrl, CommProxyStorage.I.ProtocolSetup, false);
            _asteriskProxy = _connection.CreateProxy<BI.IAsteriskProxy>();

(The protocol is TcpDuplexClientProtocolSetup with encryption set to true.)

I have a Timer with a short interval (100 milliseconds) check for channels that are disconnected (a flag set by the Disconnection event) and try to create a new connection.  When there is a disconnection, the thread count goes steadily upwards, and when there is a connection possible, the code works fine to create a new, working connnection, but the "extra threads" remain. I don't think that the Timer itself is the cause of the extra threads. 

Could this be an issue with Zyan, and how can I resolve this?  I'd like an effective way to restore a connection that has been lost without increasing the thread count in a "permanent" way.

**Comment by yallie** [comment]
Hello!

>I don't think that the Timer itself is the cause of the extra threads.

I'm almost sure that it's the timer.

It generates 10 events per second, while the socket timeout is like 15-30 seconds.
So it should spawn a few hundreds of threads just waiting for the socket to time out.
Please conduct a small experiment: get rid of the timer, and I bet your threads will be gone.

Regards, Alex

**Comment by emlrsua** [comment]
I agree that the Timer was a problem after all, due to the long socket timeouts. So, how should I handle disconnections?

Let's say that a service with the Zyan host is no longer reachable for whatever reason, but it might return sometime in the future.  The ZyanConnection object in a client starts to produce one Disconnection event after another (if I set the Retry property on DisconnectedEventArgs to true).  What should I do to keep Zyan trying to restore the connection, but without the burden of steadily increasing threads or CPU consumption?

I was thinking that on the second Disconnection event I would simply try to recreate the connection so that I could get around the socket timeout.  Also, I didn't trust the connection object to keep trying indefinitely to restore the connection, and that is another reason why I had created the timer, so that the client would keep on trying to do something to re-establish communications.

What should I do? Nothing, and hope that the connection will be re-established automatically whenever the host is reachable again?  Or should I have a timer, but it only tries to create a new connection after Disconnect events haven't been seen for a while?  Should I use the Reconnect method instead of creating a new connection?

I'm not sure what best practices are.

**Comment by yallie** [comment]
Hello,

>I didn't trust the connection object to keep trying indefinitely to restore the connection, and that is another reason why I had created the timer

Well, ZyanConnection itself uses the timer for polling the server, so you basically just recreated the built-in mechanism yourself.

>I'm not sure what best practices are.

[Here is the gist](https://gist.github.com/yallie/437ea4c087725693e1c2) that contains everything you need to reconnect automatically. Compile and play with it to see how it works (note that it sets the polling interval to 1 second for demo purposes, you'll probably want to set it to a bigger value, comparable to the socket timeout). Here is the checklist of what you need to do in your code to set things up:

### Client-side

* Add event handlers to ZyanConnection.Disconnected and Reconnected.
* Make sure Disconnected event handler sets e.Retry to true!
* Set ZyanConnection.PollingEnabled to true (heartbeat feature is disabled by default).
* Adjust ZyanConnection.PollingInterval as needed (it defaults to 1 heartbeat per minute).
* Add an event handler to ZyanConnection.NewLogonNeeded event to handle server restart!

### Server-side

* Add an event handler to host.ClientHeartbeatReceived event.
* To enable polling diagnostics, set ZyanComponentHost.PollingEventTracingEnabled to true (optional).

P.S. NewLogonNeeded event is essential if your server requires authentication. When the server is restarted, the list of client sessions is lost, so the client has to re-login. Handling this event you can either prompt the user for password or supply the password he previously entered. ZyanConnection itself doesn't store the user credentials unless `AutoLoginOnExpiredSession` is set to true. This is kinda for security purposes (i.e. against dumping the process memory to find out what's the password).

**Comment by yallie** [comment]
Feel free to reopen if you have any further questions. Thanks!

**Comment by bddckr** [comment]
For anyone coming across this in the future:
You really need that subscription to `NewLogonNeeded`! **Even when you don't do any authentication at all** because of this (at the time of writing)
https://github.com/zyanfx/Zyan/blob/b8d9e6b409695f62627fe0ca7d09a6247b33d096/source/Zyan.Communication/ZyanConnection.cs#L946-L961
https://github.com/zyanfx/Zyan/blob/b8d9e6b409695f62627fe0ca7d09a6247b33d096/source/Zyan.Communication/ZyanConnection.cs#L763-L778
