### ISSUE TITLE
Hanging client side 

### ISSUE THREAD

**Issue by abofaliha** [zyanfx/Zyan#23]
Hello .

I'm using Zyan with my chat service but when i create ZyanConnection in client side the connection is established between server and the client but the program is just hanging and no more executing ,But when i tried to connect to other service with other IP and the other one is also using Zyan it worked fine,Anyone can help me with this please?

Thank you/Hassan.

**Comment by yallie** [comment]
Hassan,

it's hard to say what is wrong based on the information you provided.
Have you tried running the program under the debugger?
When you pause the running process, you can examine all threads
and check what every thread is doing. When a thread hangs indefinitely,
it may be a [deadlock](https://en.wikipedia.org/wiki/Deadlock).

**Comment by abofaliha** [comment]
Hej @yallie  .

I fixed it the reason was the host server for chat service has the same port number to ZyanComponentHost so that it was just hanging but when i changed the port number it worked fine then. 

Thank you for your response/Hassan.

**Comment by yallie** [comment]
Hello Hassan,

Glad you've found the reason!
Thanks for reporting that.

Regards, Alex
