### ISSUE TITLE
Register components with two interfaces

### ISSUE THREAD

**Issue by Biosynth** [zyanfx/Zyan#24]
Hello Alex,

is it possible to register a component as a singleton but accessible via two different interfaces?

Let's say we have the following interfaces and classes:

IFoo.cs
```
public interface IFoo
{
    string Echo(string text);
    Action<string> Bar { get; set; } 
}
```
IFoo2.cs
```
public interface IFoo2
{
    Action<string> Bar2 { get; set; } 
}
```

Foo.cs

```
public class Foo : IFoo, IFoo2 
{
    public Action<string> Bar { get; set; }
    public Action<string> Bar2 { get; set; }
    public Guid Echo(string text)
    {
        Bar?.Invoke(text);
        Bar2?.Invoke(text);
        return text;
    }
}
```
I now want to register the component Foo somehow like
```
ZyanComponentHost Host = ...
Host.RegisterComponent<IFoo, Foo>(ActivationType.Singleton);
Host.RegisterComponent<IFoo2, Foo>(ActivationType.Singleton);
```

so that two different clients can connect to the the same instance of Foo but using different interfaces for the Proxy.

Is that possible?

Regards
Alex :)

**Comment by yallie** [comment]
Hello Alex,

```c#
var service = new Foo();
host.RegisterComponent<IFoo, Foo>(service);
host.RegisterComponent<IFoo2, Foo>(service);
```

The complete code sample: [test.cs](https://gist.github.com/yallie/88b269f320326bf4fb0b2c2e46170fba)

Regards, Alex
