### ISSUE TITLE
ZyanComponentHost memory leak

### ISSUE THREAD

**Issue by EynsherKiel** [zyanfx/Zyan#26]
Code from demo : 
var host = new ZyanComponentHost("ZyanDemo", 8080);

If ZyanComponentHost was created, then all is fine. But if we only launch our service and connection was not created, then we will have memory leak. in Zyan I'm not found how check URL and I create ZyanComponentHost in while in my Task with Thread.Sleep in 1 second. And I have memory leak. For services it's huge problem. Need mechanism check availability URL or fix memory leak.

**Comment by yallie** [comment]
Hello,

sorry for my late reply. Currently on vacation, with some poor internet...

>If ZyanComponentHost was created, then all is fine. But if we only launch our service and connection was not created, then we will have memory leak.

Don't quite understand the issue. Once you executed the constructor, the host is created, that's it. To shut it down cleanly, you have to dispose the host instance.

>in Zyan I'm not found how check URL and I create ZyanComponentHost in while in my Task with Thread.Sleep in 1 second.

That's the cause of your memory leak. Don't create multiple hosts, and you won't get a leak.

>Need mechanism check availability URL or fix memory leak.

Sorry, what's that availability URL is about?

Do you need to check whether your ZyanComponentHost is serving the incoming connections on specific URL? You can create a ZyanConnection to that URL: if it doesn't throw an exception, then the URL is available.

**Comment by EynsherKiel** [comment]
A simple example.
![code](https://user-images.githubusercontent.com/19375839/28250930-30b7585e-6a7c-11e7-93f2-7b54a9cb1848.jpg)
