### ISSUE TITLE
ZyanConnection memory leak

### ISSUE THREAD

**Issue by EynsherKiel** [zyanfx/Zyan#29]
A simple sample.
![code](https://user-images.githubusercontent.com/19375839/28250992-dde57e70-6a7c-11e7-9903-28fe1d54cf94.jpg)

P.S. Sorry for open issue where say what leak memory in ZyanConnectionHost. It's all my fault.

**Comment by yallie** [comment]
Now that makes sense, thank you!  

I agree that constructor that can throw an exception is the problem of Zyan API. When the constructor is aborted, no connection object is returned, hence, nothing to dispose. It's a known anti-pattern, but it's there from the start of the project, so we have to keep the API for backwards compatibility.

Any ideas how to fix that while keeping the old API/semantic intact (or perhaps close enough to the original?

**Comment by EynsherKiel** [comment]
Just try catch in ctor and dispose all resources in catch. And throw again.
And create static method check availability connection! It's will be soo cool :)

**Comment by yallie** [comment]
>Just try catch in ctor and dispose all resources in catch. And throw again.

Yeah, that's a good idea, thanks!

>And create static method check availability connection! It's will be soo cool :)

I don't think that's possible because URLs are protocol-dependent. Even if someone is listening on the given URL/port it doesn't mean that you can connect to that URL, so the only way to check that for sure — is to try to connect.

**Comment by yallie** [comment]
>Just try catch in ctor and dispose all resources in catch. And throw again.

I looked at the sources and it seems to be already done: [ZyanConnection.cs, line 230](https://github.com/zyanfx/Zyan/blob/master/source/Zyan.Communication/ZyanConnection.cs#L230).  

So could you be more specific about the memory leak?  
What exactly leaks in your case and how did you confirm that?

**Comment by yallie** [comment]
>And create static method check availability connection! It's will be soo cool :)

Here you are:

```c#
public static bool IsServerRunning(string url)
{
	if (string.IsNullOrWhiteSpace(url))
	{
		throw new ArgumentNullException("url");
	}

	Uri uri;
	try
	{
		uri = new Uri(url);
	}
	catch (Exception ex)
	{
		throw new ArgumentException("url", ex);
	}

	try
	{
		using (var tcp = new TcpClient())
		{
			tcp.Connect(uri.Host, uri.Port);
			return true;
		}
	}
	catch
	{
		return false;
	}
}
```

Usage example:

```c#
var result = IsServerRunning("tcpex://localhost:1234/SomeServer");
Console.WriteLine(result);
```

A few notes.

* The method checks whether some server is listening on the given endpoint.
* It doesn't check whether the server implements certain Zyan protocol.
* It doesn't support non-TCP based urls, IPC for example.
* Url prefix is ignored, so it should work with `tcp://`, `tcpex://`, `http://`, whatever.
* The method is kinda slow when the server is not available (has to wait for TCP connect timeout).

Feel free to use and/or modify according to your specific needs.

**Comment by EynsherKiel** [comment]
Hello, yallie! 

Thank you for glad news! 
IsServerRunning I will testing.

When I'm will come home I will fork / create branch project and show you where memory leak in code. 


![memoryleak](https://user-images.githubusercontent.com/19375839/28401419-7f1ac0aa-6d22-11e7-8722-82a9b9a6e8ac.png)

**Comment by EynsherKiel** [comment]
Hello!
Code for test. 
In TaskManager you may observe memory leak.
```c#
    public class ZyanConnectionFactory
    {
        private readonly ZyanConnectionSetup _setup;

        public ZyanConnectionFactory(ZyanConnectionSetup setup)
        {
            _setup = setup;
        }

        public async Task<ZyanConnection> CreateConnection()
        {
            return await Task.Factory.StartNew(() => Connection(_setup));
        }


        private ZyanConnection Connection(ZyanConnectionSetup setup)
        {
            while (true)
            {
                try
                {
                    return new ZyanConnection(setup);
                }
                catch
                {
                    Thread.Sleep(1000);
                }
            }
        }
    }

    public class ServiceFactory
    {
        private readonly string _uri;
        private readonly ZyanConnectionFactory _factory;

        public ServiceFactory(string uri)
        {
            _uri = uri;

            var protocol = new TcpDuplexClientProtocolSetup(true)
            {
                TcpKeepAliveEnabled = true,
                TcpKeepAliveInterval = 1000,
                MaxAttempts = int.MaxValue,
            };

            var setup = new ZyanConnectionSetup()
            {
                AutoLoginOnExpiredSession = true,
                KeepSessionAlive = true,
                ProtocolSetup = protocol,
                ServerUrl = _uri
            };

            _factory = new ZyanConnectionFactory(setup);
        }

        public string URI => _uri;

        public async Task<ZyanConnection> CreateConnectionAsync()
        {
            var connection = await _factory.CreateConnection(); 

            return connection;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var name = System.Net.Dns.GetHostName();

            string uri = $"tcpex://{name}:8210/Test service";

            var factory = new ServiceFactory(uri);

            factory.CreateConnectionAsync().ContinueWith(task => Console.WriteLine("WTF"));

            Console.ReadLine();
        }
    }
```

**Comment by yallie** [comment]
Thanks for the code! Will have a look.
