### ISSUE TITLE
Zyan exception {"Public key changed since the message was encrypted."}

### ISSUE THREAD

**Issue by abofaliha** [zyanfx/Zyan#31]
Hey. 

Before a while i got this exception and then i had the client and server and Interface on the same assembly. 
And i have fixed it by using Tcp and Ipc protocols but i have no idea about the published component has Tcp or Ipc protocol or the same component which published by using TCP only?
After that i have separated them i mean client has his own assembly also interface and server and tried to use Tcp protocol only but i'm still getting the same exception.
Can you help me please?

regards/Hassan.

**Comment by yallie** [comment]
>Public key changed since the message was encrypted.

Looks like you're using duplex TCP channel as a client and as a server in the same 
process (or, more accurate, in the same AppDomain). Duplex TCP channel doesn't 
support this mode. So you'll have to switch either to simplex TCP, or to IPC channel.

Perhaps it's what you've already done.

>but i have no idea about the published component has Tcp or Ipc protocol or 
>the same component which published by using TCP only?

If you have one ZyanComponentHost instance, then you have one protocol.
It's either TCP or IPC, but not both.

>After that i have separated them i mean client has his own assembly also interface 
>and server and tried to use Tcp protocol only but i'm still getting the same exception.

Make sure your client and your server have exactly the same settings.
I.e. same protocol at both ends, same encryption, compression flags.

Try building your application step by step. Start off with the simplest possible project.
One interface, one method, default TCP protocol. Make sure it works fine.
If you're struggling to set it up, use Zyan sample project as a template.

Then change your setup one step at a time. Add more interfaces and components.
Enable duplex protocol at both client and server, etc. Hope that helps.

**Comment by abofaliha** [comment]
Looks like you're using duplex TCP channel as a client and as a server in the same
process (or, more accurate, in the same AppDomain). Duplex TCP channel doesn't
support this mode. So you'll have to switch either to simplex TCP, or to IPC channel.

Sorry what do you mean with simplex TCP ? 

before i fixed with these code
var tcpProtocol = new TcpDuplexServerProtocolSetup (port, employeeService, true); 
var tcpHost = new ZyanComponentHost ("ITJH", tcpProtocol); // for remote connections

var ipcProtocol = new IpcBinaryServerProtocolSetup("AnyPortName");
var ipcHost = new ZyanComponentHost("ITJHIpc", ipcProtocol, tcpHost.ComponentCatalog); // for local machine connections

and i have one ZyanComponentHost so which protocol has this component ? is it Tcp or Ipc ?

Regards/Hassan.

**Comment by yallie** [comment]
>Sorry what do you mean with simplex TCP ?

Simplex = non-duplex :)

`TcpDuplexClientProtocolSetup` is a duplex channel (uses one socket for sending data in both
directions, from client to server and from server back to client). `TcpCustomClientProtocolSetup` 
and `TcpBinaryClientProtocolSetup` are two kinds of the simplex channel (they use one socket 
for sending, and another socket for receiving the data).

Standard remoting TCP channel is simplex. Duplex TCP channel implemented in Zyan
solves some problems of the simplex channel, but it has its limitations. One of these
limitations is that you can't have both client and server inside the same AppDomain.
So in that case you just use one of the standard channels that don't have this limitation.

>and i have one ZyanComponentHost so which protocol has this component ? is it Tcp or Ipc ?

You posted the code where you have two ZyanComponentHosts:

```c#
var tcpProtocol = new TcpDuplexServerProtocolSetup (port, employeeService, true);
var tcpHost = new ZyanComponentHost ("ITJH", tcpProtocol); // #1

var ipcProtocol = new IpcBinaryServerProtocolSetup("AnyPortName");
var ipcHost = new ZyanComponentHost("ITJHIpc", ipcProtocol, tcpHost.ComponentCatalog); // #2
```

As long as both `tcpHost` and `ipcHost` are running, your component is accessible 
via both protocols. Both with TCP and IPC.

The component is the same, but is published on two different protocol endpoints.
If it's registered as a singleton, you'll get the same instance serving your requests,
no matter which protocol is used to connect to it.

Hope that answers your question :)

Regards, Alex

**Comment by abofaliha** [comment]
Hey yallie.

I used simplex TcpCustomClientProtocolSetup and it worked fine so i have to say thanks for helping and for supporting.

Regards/Hassan.

**Comment by yallie** [comment]
Great!
