### ISSUE TITLE
ZyanConnection with Auth results in "Attempting to deserialize empty stream"

### ISSUE THREAD

**Issue by Kempeth** [zyanfx/Zyan#33]
My Server Code:

            var authProv = new DBAuthenticationProvider(); // Doesn't work with either...
            //var authProv = new BasicWindowsAuthProvider();
            var protocolSetup = new TcpCustomServerProtocolSetup(8080, authProv);

            host = new ZyanComponentHost("DaMaSchGameServer", protocolSetup);
            Console.WriteLine("Host up");

            host.RegisterComponent<Services.ITimeService, Services.TimeService>();
            Console.WriteLine("Service up");

            Console.ReadKey();
            Console.WriteLine("Shutting down");
            host.UnregisterComponent<Services.ITimeService>();

My Client code:

            var credentials = new Hashtable();
            credentials.Add(AuthRequestMessage.CREDENTIAL_USERNAME, "username");
            credentials.Add(AuthRequestMessage.CREDENTIAL_PASSWORD, "hunter2");

            var protocolSetup = new TcpCustomClientProtocolSetup(false);

            // The following line produces the error:
            connection = new ZyanConnection(
                "tcp://localhost:8080/DaMaSchGameServer",
                protocolSetup,
                credentials,
                false,
                true);

            timeservice = connection.CreateProxy<GameServer.Services.ITimeService>();

When I don't use Authentication everything works. But when I use my own AuthProvider or the BasicWindowsAuthProvider I get this exception:

    Attempting to deserialize an empty stream.

> Server stack trace: 
>    bei System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
>    bei System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryRequestMessage(String objectUri, Stream inputStream, Boolean bStrictBinding, TypeFilterLevel securityLevel)
>    bei System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)
> 
> Exception rethrown at [0]: 
>    bei System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    bei System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    bei Zyan.Communication.IZyanDispatcher.Logon(Guid sessionID, Hashtable credentials)
>    bei Zyan.Communication.ZyanConnection..ctor(String serverUrl, IClientProtocolSetup protocolSetup, Hashtable credentials, Boolean autoLoginOnExpiredSession, Boolean keepSessionAlive) in D:\Externals\Zyan\source\Zyan.Communication\ZyanConnection.cs:Zeile 228.
>    bei Zyan.Communication.ZyanConnection..ctor(String serverUrl, IClientProtocolSetup protocolSetup, Hashtable credentials, Boolean autoLoginOnExpiredSession, Boolean keepSessionAlive) in D:\Externals\Zyan\source\Zyan.Communication\ZyanConnection.cs:Zeile 240.
>    bei ClientWindows.Program.Main() in C:\Users\dschachtler\Documents\Visual Studio 2015\Projects\ZyanGameNetwork\ClientWindows\Program.cs:Zeile 30.
>    bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>    bei System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
>    bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>    bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    bei System.Threading.ThreadHelper.ThreadStart()

**Comment by yallie** [comment]
Hello @Kempeth,

>Attempting to deserialize an empty stream.

That error means that you have different encryption settings at client and server.
Encryption should be either enabled or disabled on both sides.
Unencrypted client won't connect to the encrypted server.

>var protocolSetup = new TcpCustomServerProtocolSetup(8080, authProv);

Try replacing that with `new TcpCustomServerProtocolSetup(8080, authProv, encryption: false)`.

Regards, Alex

**Comment by yallie** [comment]
Feel free to reopen the issue if you have further question! Thanks.
