### ISSUE TITLE
NIC selection for protocols when creating a channel

### ISSUE THREAD

**Issue by lzaiats** [zyanfx/Zyan#35]
Just wanted to propose new constructors for all (network interface based) protocol implementations to allow you to specify wich NIC (ip address) you want the channel to binds to ;)

I did it by myself here, but i think it will be cool to others have this possibility!

`_channelSettings["bindTo"] = _ipAddress;`

when calling _channelFactory on

`public override IChannel CreateChannel()`

my version now is just like this:

`_protocol = new TcpBinaryServerProtocolSetup(ipAddress, port);`

BTW, you guys did a great job with this framework! I am currently using it as our MMORPG game servers P2P backend, for handover networked objects between servers ;)

**Comment by yallie** [comment]
Great! :)

As always, glad to hear that the code is used in production!

>my version now is just like this:

May I ask for a pull request?

Thanks :)

**Comment by lzaiats** [comment]
Done!

**Comment by yallie** [comment]
Thanks a lot!
