### ISSUE TITLE
Performance after Decompression

### ISSUE THREAD

**Issue by csharpdeveloper12** [zyanfx/Zyan#38]
Hi yallie,

i have an issue in the client after decompression.

I have include the source code of zyan in my project and have set break points.

In my project i have realized a performance issue:

1. Server: reads data from sql server, created objects from the results and sends the objects in a list to the client (duration: 2 seconds) ok
2. Client: zyan receives data and decompress data (duration: < 1 second) ok
3. Client: zyan works with the data and gives the data to my project (duration: 2 - 3 seconds) slow?

The compressed data size is: 0,81 MB and after descompression in the client 3,93 MB.

Points 1 and 2 are ok but point 3 is, in my view in this project, too slow?

Please can you check, whether there is an performance lack after decompression?
Because the performace until after the descompression is very good :)

Many thanks in advance

**Comment by yallie** [comment]
Hello,

I'm not sure what do you mean in p. 3 — zyan works with the data?

Zyan itself doesn't have any data processing except of the compression: only the standard serialization and deserialization using the binary formatter. By the way, classes with custom serialization (implementing `ISerializable` interface) may affect the performance. In our past projects (few years ago) we had troubles with the standard `DataSet` and `DataTable` classes, so we had to define derived classes and reimplement the `ISerializable` interface properly, with reference tracking, etc.

If you're suspecting that compression may cause the performance degradation, please try disabling the compression in the protocol by setting the `CompressionMethod` property to `CompressionMethod.None` on both ends (client and server protocols).

P.S. I certainly agree that 2-3 seconds is way too slow for 3,93 megabytes of data. The timing should be within a few milliseconds range on modern computers.

**Comment by csharpdeveloper12** [comment]
Hi :)

first, tank you for your answer. The system in an virtualized AMD Ryzen Threadripper with 8 cores in the vm. The transfered objects are "normal" classes; no `DataSet` or `DataTable`.

'sry for my late answer but now with example ;)

```
Zyan.Communication.ZyanProxy
private ReturnMessage InvokeRemoteMethod(IMethodCallMessage methodCallMessage)
{
System.Diagnostics.Trace.WriteLine("InvokeRemoteMethod Start: " + System.DateTime.Now);
...
System.Diagnostics.Trace.WriteLine("BeforeInvoke: " + System.DateTime.Now);
returnValue = _remoteDispatcher.Invoke(trackingID, _uniqueName, correlationSet, methodCallMessage.MethodName, genericArgs, paramTypes, checkedArgs);
System.Diagnostics.Trace.WriteLine("AfterInvoke: " + System.DateTime.Now);
...
var retVal = new ReturnMessage(returnValue, null, 0, methodCallMessage.LogicalCallContext, methodCallMessage);
System.Diagnostics.Trace.WriteLine("InvokeRemoteMethod End: " + System.DateTime.Now);
return retVal;
}
```

```
Zyan.Communication.Toolbox.Compression.CompressionHelper
public static Stream Decompress(Stream inputStream, CompressionMethod level = CompressionMethod.Default)
{
...
case CompressionMethod.DeflateStream:
{
System.Diagnostics.Trace.WriteLine("BeforeDecompression: " + System.DateTime.Now);
System.Diagnostics.Trace.WriteLine("InputStream Size: " + inputStream.Length);
var stream = new MemoryStream();
using (var output = new DeflateStream(inputStream, CompressionMode.Decompress, true))
{
int read;
var buffer = new byte[BufferSize];
while ((read = output.Read(buffer, 0, BufferSize)) > 0)
{
stream.Write(buffer, 0, read);
}
}
stream.Seek(0, SeekOrigin.Begin);
System.Diagnostics.Trace.WriteLine("AfterDecompression: " + System.DateTime.Now);
System.Diagnostics.Trace.WriteLine("Stream Size: " + stream.Length);
return stream;
}
...
}
```

That are the "break point results" in the client:
> InvokeRemoteMethod Start: 23.01.2018 11:31:35
	BeforeInvoke: 23.01.2018 11:31:35
		BeforeDecompression: 23.01.2018 11:32:29 - InputStream Size: 18748340
		AfterDecompression: 23.01.2018 11:32:31 - Stream Size: 71097982
	AfterInvoke: 23.01.2018 11:35:19
InvokeRemoteMethod End: 23.01.2018 11:35:19

The decompression Task are very fast (2 seconds for 18 MB -> 68 MB) 👍
But after the decompression it works 3 minutes until the end of `InvokeRemoteMethod` is reached.
Maybe its an issue in the remoting of .net?

**Comment by yallie** [comment]
Oh, I see. Yes, I believe it's a slow deserialization. 
But again, it's too slow — 68 megabytes isn't too much data to handle.
I'm sure the timing can be greatly improved.

What kind of data are you serializing?
Have you tried to serialize/deserialize the data locally, without Zyan?
Please try benchmarking the deserialization of your data like this:

1. Save your decompressed stream to a file (68 megabytes)
2. Write a separate console program like this:

```csharp
void Benchmark(string fileName)
{
   var fmt = new BinaryFormatter();
   var stream = File.OpenRead(fileName);
   var sw = Stopwatch.StartNew();
   var obj = fmt.Deserialize(stream);
   sw.Stop();

   Console.WriteLine("Deserialization time: {0}", sw.Elapsed);
}
```

PS. Also, I'd recommend using a perf profiler instead of the Stopwatch :)

**Comment by csharpdeveloper12** [comment]
I load data from a MS SQL Server with NHibernate and send this data to the client.
These are "normal" data with standard properties (string, DateTime, ISet<T>).

The created file has a size from 69432 KB.
The deserialization lasts 00:02:44.5245693.

Of course, the `Stopwatch` isnt the best tool for this. But i think its exactly enough for this task ;)

**Comment by yallie** [comment]
Ok, so this is the deserialization issue.
What about the "normal" data — you mean POCO classes like this?

```csharp
public class MyTable
{
     public string Name { get; set; }
     public DateTime BirthDate { get; set; }
}
```

**Comment by yallie** [comment]
Yep, the deserialization of this size using BinaryFormatter is very slow.
Here is my quick benchmark results:

```
Serialization: 3.67 seconds
File size: 60,389,068 bytes
Deserialization: 3:53.62 seconds
```
The code for my benchmark:
```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;

[Serializable]
public class MyPoco
{
	public string Name { get; set; }
	public DateTime BirthDate { get; set; }
}

class Program
{
	static void Main()
	{
		Serialize();
		Deserialize();
	}

	static void Serialize()
	{
		var fmt = new BinaryFormatter();
		using (var stream = File.Create("test.dat"))
		{
			var objects = Pocos().Take(1500000).ToArray();
			var sw = Stopwatch.StartNew();
			fmt.Serialize(stream, objects);
			sw.Stop();

			Console.WriteLine("Serialization: {0} seconds", sw.Elapsed);
			Console.WriteLine("File size: {0} bytes", stream.Length);
		}
	}

	static void Deserialize()
	{
		var fmt = new BinaryFormatter();
		using (var stream = File.OpenRead("test.dat"))
		{
			var sw = Stopwatch.StartNew();
			var objects = fmt.Deserialize(stream);
			sw.Stop();

			Console.WriteLine("Deserialization: {0} seconds", sw.Elapsed);
		}
	}

	static IEnumerable<MyPoco> Pocos()
	{
		var counter = 0;
		while (true)
		{
			yield return new MyPoco
			{
				Name = "MyPoco" + ++counter,
				BirthDate = DateTime.Now
			};
		}
	}
}
```

**Comment by csharpdeveloper12** [comment]
Correct, POCO classes.
With `[Serializable]` and the classes implements `INotifyPropertyChanged`.

Wow, the `BinaryFormatter` is slow.
Fortunately, the issue does not come from Zyan but from the `BinaryFormatter` :)

At the Moment i try the Performance when i de-/serialize the returned object with Json.Net...

**Comment by yallie** [comment]
Ok, how to solve this?

I think you can try registering other serializers for your objects.
Zyan has a concept of serialization handlers, see [SerializationHandlerRepository.cs](https://github.com/zyanfx/Zyan/blob/master/source/Zyan.Communication/SerializationHandlerRepository.cs).

You'll need to use some kind of a fast serializer, like Wire, Hyperion or Protobuf.
Define a [serialization handler](https://github.com/zyanfx/Zyan/blob/master/source/Zyan.Communication/ISerializationHandler.cs) for your objects and register it on both client and server.
Registration looks like this: [ZyanComponentHost.cs, like 574](https://github.com/zyanfx/Zyan/blob/master/source/Zyan.Communication/ZyanComponentHost.cs#L574).

**Comment by yallie** [comment]
Json.NET is also good, but you'll probably get twice as more payload (~100-150 mb).

**Comment by csharpdeveloper12** [comment]
That sounds good :)
I will try it with my own `serialization handler`.
Thank you for your time and your help :)

**Comment by yallie** [comment]
You're welcome :)
