### ISSUE TITLE
Xamarin.iOS compatibility

### ISSUE THREAD

**Issue by WeitesFeld** [zyanfx/Zyan#39]
Hello,

I would like to ask if there are any chances for Xamarin.iOS compatibility, is it just untested or will it not work by design? I want to develop a project which has a Xamarin.iOS server and different client platforms (e.g. Xamarin.iOS, Xamarin.Android and plain old Windows C#.)

Another question: Are there any plans to support .NET Standard?

Thanks

**Comment by yallie** [comment]
Hello,

Sorry to say, but Xamarin.iOS is not likely to be ever supported using the current technology stack: Zyan uses runtime code generation, and iOS only supports ahead of time compilation. Supporting iOS means using pre-generated proxy classes.

About .NET Core — I have a prototype/sketch for the next version of Zyan running on .NET Core. It's still very limited (only RPC is currently supported, no LINQ, no events, no sessions, no authentication, etc). So if all you need is just remote calls, you can give it a try. The good thing is that the new version uses ZeroMQ as an underlying protocol, so it should be much faster than Remoting-based original Zyan library.

The .NET Core project is here: https://github.com/yallie/Zyanea
