### ISSUE TITLE
Timeline for release 2.11

### ISSUE THREAD

**Issue by heikar** [zyanfx/Zyan#49]
Hi yallie,

are you planning the release of the version 2.11?

The implementation of SRP-6a is verry great and i would like to use it via NuGet.

Thank you and many greetings.

heikar

**Comment by yallie** [comment]
Hi @heikar,

thanks for your kind words :)

No problem, I can publish v2.11 package.
I'm using custom builds in my apps, that's why I still didn't publish it on Nuget.

**Comment by yallie** [comment]
Uploaded the Nuget package: https://www.nuget.org/packages/Zyan/2.11.0

**Comment by heikar** [comment]
Hi @yallie,

thanks a lot for the fast publishing and for the new functions :)
