### ISSUE TITLE
any .net core migration?

### ISSUE THREAD

**Issue by jingyiliu** [zyanfx/Zyan#50]
any plan to migrate to .net core?

**Comment by yallie** [comment]
Zyan uses a lot of APIs not available in .NET Core.
So most likely, it can't be directly ported on .NET Core and iOS.

Some time ago I started a new project from scratch to run on .NET Core.
It's currently early alpha and it's not supposed to be backwards-compatible with Zyan.
It still lacks session management and other advanced Zyan features, it's plain RPC.

You may have a look at it here: https://github.com/yallie/Zyanea
I'm going to move it to zyanfx organization when it reaches beta version.
