### ISSUE TITLE
Error while create authentication provider

### ISSUE THREAD

**Issue by heikar** [zyanfx/Zyan#54]
Hi yallie,

at first, i wish you a happy new year and all the best for 2019 :)

I dont know if its the same as your issue [https://github.com/zyanfx/Zyan/issues/53](url). If you meant the same thing, then you can close this issue.

When i instantiate a new `SrpAuthenticationProvider` the following error appear:

> System.MissingMethodException:
> "Void SecureRemotePassword.SrpParameters..ctor(System.Security.Cryptography.HashAlgorithm, System.String, System.String, System.Nullable`1<Int32>)"

The used version of srp is 1.0.4; with 1.0.2 it works perfect.

Many Greetings
heikar

**Comment by yallie** [comment]
Hello @heikar,

thanks for getting in touch! Happy New year :)

>When i instantiate a new SrpAuthenticationProvider the following error appear

Too bad, looks like I screwed up the backwards compatibility in SrpParameters class 😲
I'll update Zyan to match the latest srp.net package by the weekend.
In the meantime, please use srp version 1.0.2 if possible.

Sorry for the inconvenience!

**Comment by heikar** [comment]
Hi @yallie ,

that's great. Thank you :)

The behavior ist not really an inconvenience. The only thing is that i have to watch when i update the NuGet-Packages, that version 1.0.4 is excluded ;)
