### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by heikar** [zyanfx/Zyan#55]
Hi yallie,

what think you about an imlpementation of a two factor authentication in Zyan?

I think whether it is possible to add a new interface e.g. "ITwoFactorAuthenticationProvider" with an method to create a TFA-Key and add a new class e.g. "TwoFactorAuthenticationCredentials".

In "ZyanConnection" you could provide a parameter for "TwoFactorAuthenticationCredentials" and "ZyanComponentHost" you could provide a parameter for "ITwoFactorAuthenticationProivider".
On login Zyan checks the passed credentials in the "ITwoFactorAuthenticationProvider"-Implementation.

That is only an idea/consideration of me. What do you think about it?

Many Greetings
heikar

**Comment by yallie** [comment]
Hi @heikar,

thanks for the suggestion!

Actually, one of my apps implements a two-factor authentication using Zyan.
My custom `AuthProvider` supports two authentication steps.
The first authentication step checks the password, generates the 2fa code,
sends an SMS to a user and fails with a custom `TwoAuthCodeRequiredException`.
The second step succeeds and completes the authentication.

The trick is to interpret the authentication step based on the presence of the 2fa key.
If user's credentials contains name+password, it's the first step.
If user's credentials include 2fa key in addition to name and password, its the second step.
All interaction between client and server is carried out by custom credentials class.

So I'd like to keep `IAuthProvider` interface simple and stateless.
Let me know if you need help implementing custom 2fa provider.

Regards, Alex

**Comment by heikar** [comment]
Hi Alex,

thank you for your reply and your help :)

At the moment, i am in another project, but i will try it with an own `AuthProvider`.

My concerns are, how can i divide the login process in multiple (two) steps?
Step 1: The user make a login with username and password.
Step 2: If step 1 is ok then stop the process and generate a key in the server to check it in step 3.
Step 3: The user performs an second login with the "user generated" key.

- But how i can intercept it in step 2?
- Must the user two times invoke `ZyanConnection`?

Regards
heikar

**Comment by yallie** [comment]
Hi @heikar ,

>But how i can intercept it in step 2?
>Must the user two times invoke `ZyanConnection`?

No, `ZyanConnection` is created only once.
Two-step login process is performed by custom credentials class.
Here is how it works.

Server-side: custom `IAuthenticationProvider` implementation:
```csharp
class MyAuthProvider : IAuthenticationProvider
{
	public AuthResponseMessage Authenticate(AuthRequestMessage authRequest)
	{
		var login = authRequest.Credentials["username"] as string;
		var password = authRequest.Credentials["password"] as string;
		var code = authRequest.Credentials["code"] as string;

		if (code == null)
		{
			return HandleStep1(login, password);
		}

		return HandleStep2(login, password, code);
	}

	private AuthResponseMessage HandleStep1(string login, string password)
	{
		if (login == "hacker" && password == "secret")
		{
			// TODO: generate 2fa code, save it, send SMS to a user, etc
			return new AuthResponseMessage
			{
				Success = true,
				Completed = false // second step is pending
			};
		}

		return new AuthResponseMessage
		{
			Success = false,
			Exception = new AccountNotFoundException()
		};
	}

	private AuthResponseMessage HandleStep2(string login, string password, string code)
	{
		if (login == "hacker" && password == "secret")
		{
			// here: validate the 2fa code created on Step1
			return new AuthResponseMessage
			{
				Success = true,
				Completed = code == "1234"
			};
		}

		return new AuthResponseMessage
		{
			Success = false,
			Exception = new AccountNotFoundException()
		};
	}
}
```

Client-side: custom credentials class:
```csharp
class MyCredentials : AuthCredentials
{
	public override void Authenticate(Guid sessionId, IZyanDispatcher dispatcher)
	{
		// give a user maximum of 3 retries to enter the SMS code
		for (var i = 0; i < 3; i++)
		{
			// ask for 2fa code
			Console.Write("SMS code: ");
			CredentialsHashtable["code"] = Console.ReadLine();

			// try to log on
			var response = dispatcher.Logon(sessionId, CredentialsHashtable);
			if (response.Completed && response.Success)
			{
				return; // ok, now we're logged in
			}
		}

		throw new Exception("Too bad, wrong code was specified");
	}
}
```

Client-side: establishing the connection
```csharp
// ask the user or read from a config file
var credentials = new MyCredentials
{
	UserName = "hacker",
	Password = "secret",
};

// establish connection
var protocol = new TcpDuplexClientProtocolSetup(true);
using (var conn = new ZyanConnection(url, protocol, credentials, true, true))
{
	Console.WriteLine("Connected!");
}
```

Here is the complete working example:
https://gist.github.com/yallie/e912f47042eede8cdbde31d35d45418f

**Comment by heikar** [comment]
Hi Alex,

please excuse the delay :(

Thanks a lot for the example and your work, it brings more clarity :)

One other question, when someone who use srp as authentication would use the two factor authentication too, then it breaks the mind of srp?  In srp, except of step 1, the server do not know the username, right?
Would you say one should use srp only without two factor authentication?

Many thanks and many greetings
heikar

**Comment by yallie** [comment]
Hi @heikar , no worries about the delay.

>One other question, when someone who use srp as authentication 
>would use the two factor authentication too, then it breaks the mind of srp?

Well, the built-in SRP auth provider doesn't know about the two-factor auth extensions.
I think you can extend the built-in provider to add the 2fa support.
My app uses custom auth provider for historical reasons (the provider was implemented
before I added SRP protocol support in Zyan), so I myself didn't try to extend it.

>In srp, except of step 1, the server do not know the username, right?

Zyan's SRP auth provider uses the user name only on the first step, that's right.
But when you implement 2FA you'll need your own credentials class for the client anyway.
In that custom class you can pass the user name to server as you wish, at any step.

>Would you say one should use srp only without two factor authentication?

SRP ensures that the password is not sent over the wire, that's it.
2FA ensures that the password by itself is not enough to log on.
So SRP doesn't render 2FA useless or unnecessary, these concepts are orthogonal.
Both of them improve the overall security, each in its own sense.

**Comment by heikar** [comment]
Hi @yallie ,

many thanks for your work and informations :)

I will try it on different approaches. If i need help i will tell you ;)

Many greetings,
heikar
