### ISSUE TITLE
Non-Sockets Based IPC

### ISSUE THREAD

**Issue by TonyValenti** [zyanfx/Zyan#56]
Hi @yallie -
Is there a way for me to use Zyan without needing a socket or network connection?  I'd really like to use it over named pipes.

**Comment by yallie** [comment]
Hi Tony,

yes, there's a built-in IPC transport which uses named pipes.
Use `IpcBinaryServerProtocolSetup` for server and `IpcBinaryClientProtocolSetup` for client.

Server code:
```csharp
// use any string for IPC port name (use chars valid in the file names)
var protocol = new IpcBinaryServerProtocolSetup("AnyUniqueString");

// the same server code as for any other transport
using (var host = new ZyanComponentHost("MyCoolService", protocol))
{
	host.RegisterComponent<ISampleService, SampleService>();
	Console.WriteLine("Server started. Press ENTER to quit.");
	Console.ReadLine();
}
```

Client code:
```csharp
// make sure to supply the same values for IPC port name and host name
var protocol = new IpcBinaryClientProtocolSetup();
var url = protocol.FormatUrl("AnyUniqueString", "MyCoolService");

// the same client code as for any other transport
using (var conn = new ZyanConnection(url, protocol))
{
	// now we're connected, so create a proxy and execute its methods
	var proxy = conn.CreateProxy<ISampleService>();
	proxy.HelloRemoteWorld();
}
```

Here is the complete sample code: https://gist.github.com/yallie/6065750

**Comment by TonyValenti** [comment]
Awesome!  This is really helpful!

Does this support .NET core?

**Comment by yallie** [comment]
>Does this support .NET core?

No, I'm afraid not.

.NET Core doesn't include neither remoting stack, nor transparent proxies used by Zyan.
So Zyan requires full desktop .NET Framework to run.

I'm currently experimenting with alternative RPC implementations
meant to eventually replace Zyan on .NET Core (see [Zyanea](https://github.com/yallie/Zyanea) and [JsonServices](https://github.com/yallie/JsonServices)),
but they use ZeroMQ and Websocket transport, not named pipes.

**Comment by ErrCode** [comment]
I have pretty much the same requirements as @TonyValenti. Want to use Zyan with a .NET core and for local IPC only. Would be nice to have a trimmed down nuget package of Zyan that suits this purpose.

Happy to help contribute if that is an option.

**Comment by yallie** [comment]
Hello @ErrCode ,

I'm afraid Zyan just can't be ported to .NET Core due to absence of the Remoting stack, sorry.

Of course, if you have some particular approach in mind, I'd be just glad if you give it a try :)
