### ISSUE TITLE
Multiple authentication providers

### ISSUE THREAD

**Issue by heikar** [zyanfx/Zyan#57]
Hi yallie,

it is possible for you, to implement an option to work with multiple authentication Providers?
E.g. on the server side in the `ProtocolSetup` a Parameter `AuthenticationProviderList` which is a collection of given authentication Providers with a flag (`list.Add(new TestProvider(), "TP");`).
If a client performs a Login, the Server checks which `AuthenticationProvider` uses the Client and performs the authentication check.

With this Approach it is e.g. possible to use `IntegratedWindowsAuthProvider` for users in the local Network and `SRP` for (external) users without an user profile.

What do you think about it?

Many greetings
heikar

**Comment by yallie** [comment]
Hi @heikar, that's a nice idea!

It can be implemented like this (pseudocode):

```csharp
public class MultiAuthenticationProvider : IAuthenticationProvider
{
  const ProviderKey = "Provider";

  public MultiAuthenticationProvider(params IAuthenticationProvider providers)
  {
    Providers = providers.ToDictionary(p => p.GetType().Name);
  }

  private Dictionary<string, IAuthenticationProvider> Providers { get; }

  public AuthResponseMessage Authenticate(AuthRequestMessage authRequest)
  {
    if (authRequest.Credentials == null || authRequest.Credentials[ProviderKey] == null)
    {
      return new AuthResponseMessage()
      {
        Success = false,
        ErrorMessage = "Authentication provider not specified",
        AuthenticatedIdentity = null
      };
    }

    var providerName = authRequest.Credentials[ProviderKey];
    if (!Providers.ContainsKey(providerName))
    {
      return new AuthResponseMessage()
      {
        Success = false,
        ErrorMessage = "Unsupported authentication provider: " + providerName,
        AuthenticatedIdentity = null
      };
    }

    return Providers[providerKey].Authenticate(authRequest);
  }
}
```

**Comment by heikar** [comment]
Hi @yallie,

thank you for the food for thought :)

I have implemented your pseudocode (i think, for pseudocode it is really good :)).

Two little corrections:
`public MultiAuthenticationProvider(params IAuthenticationProvider providers)`
into `public MultiAuthenticationProvider(params IAuthenticationProvider[] providers)`

`return Providers[providerKey].Authenticate(authRequest);`
into return `Providers[providerName].Authenticate(authRequest)`

And it works :)

Many thanks to you and the quick solution

Many greetings
heikar

**Comment by yallie** [comment]
You're welcome! 😄

**Comment by heikar** [comment]
Hi @yallie .

it works really good. But now i've tested it with the SRP implementation and it fails :-(

Can you please check the `SrpAuthenticationProvider`. I get an error because the credentials doesn't contains `ProviderKey`. I think the KeyValue-Pair (`ProviderKey`) get lost between the single steps, in the `Authenticate-Method` in the `SrpCredentials-Class`.

Thank you in advance :)

**Comment by yallie** [comment]
Yes, the provider key is not a built-in concept of Zyan.
That's the trick I proposed for your use case.
You'll need a custom SRP credentials class like this (pseudocode):

```csharp
public class MySrpCredentials : AuthCredentials
{
  public MySrpCredentials(string userName, string password)
  {
    UserName = userName;
    Password = password;
    SrpClient = new SrpClient();
  }

  private SrpClient SrpClient { get; set; }

  public override void Authenticate(Guid sessionId, IZyanDispatcher dispatcher)
  {
    // step #1
    var clientEphemeral = SrpClient.GenerateEphemeral();
    var request1 = new Hashtable
    {
      { ProviderKey, nameof(SrpAuthenticationProvider) },
      { SrpProtocolConstants.SRP_STEP_NUMBER, 1 },
      { SrpProtocolConstants.SRP_USERNAME, UserName },
      { SrpProtocolConstants.SRP_CLIENT_PUBLIC_EPHEMERAL, clientEphemeral.Public },
    };

    var response1 = dispatcher.Logon(sessionId, request1).Parameters;
    var salt = (string)response1[SrpProtocolConstants.SRP_SALT];
    var serverPublicEphemeral = (string)response1[SrpProtocolConstants.SRP_SERVER_PUBLIC_EPHEMERAL];

    // step #2
    var privateKey = SrpClient.DerivePrivateKey(salt, UserName, Password);
    var clientSession = SrpClient.DeriveSession(clientEphemeral.Secret, serverPublicEphemeral, salt, UserName, privateKey);
    var request2 = new Hashtable
    {
      { ProviderKey, nameof(SrpAuthenticationProvider) },
      { SrpProtocolConstants.SRP_STEP_NUMBER, 2 },
      { SrpProtocolConstants.SRP_CLIENT_SESSION_PROOF, clientSession.Proof },
    };

    var response2 = dispatcher.Logon(sessionId, request2).Parameters;
    var serverSessionProof = (string)response2[SrpProtocolConstants.SRP_SERVER_SESSION_PROOF];
    SrpClient.VerifySession(clientEphemeral.Public, clientSession, serverSessionProof);
  }
}
```

**Comment by heikar** [comment]
Sorry for the late feedback,
but thank you :) it works perfect.

Now the multi factor authentication works and the srp is ported for it :)

Thank you and best regards
heikar
