### ISSUE TITLE
Could not add Zyan package to Xamarin.Android project

### ISSUE THREAD

**Issue by raminmjj** [zyanfx/Zyan#64]
Hi.
in Nuget package manager I've got this error: "Could not install package 'Zyan.SafeDeserializationHelpers 0.5.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information"
what's the problem?
I set target version to 8.1 but I got the same message.

**Comment by yallie** [comment]
Hi @raminmjj 

You're right, SafeDeserializationHelpers package don't have a MonoAndroid target.
I think that .NET v3.5 version should work for Xamarin, so let's see if it works.

I've published a new version of SafeDeserializationHelpersPackage with Android target:
https://www.nuget.org/packages/Zyan.SafeDeserializationHelpers/0.5.1

Although I don't use Xamarin for a few years now, so I'm not sure I can test it, sorry.
Please update the package reference in your project and report back if it works for you.

**Comment by raminmjj** [comment]
Hi @yallie 
the new package worked.
thank you.
