### ISSUE TITLE
Different authentication provider for for different services

### ISSUE THREAD

**Issue by teleavtomatika** [zyanfx/Zyan#65]
Hi Alexey,
Is it possible to have different **AuthenticationProviders** for different services?
For example we want to make **IPublicService** with **NullAuthenticationProvider** and some **ISecretService** with **CustomAuthenticationProvider** on the same TCP port, is it possible?

**Comment by yallie** [comment]
Hi,

No, there is no such built-in functionality, sorry.
Authentication is made when connection is established.
Once a client is authenticated, it has access to all published services.

But it's quite easy to add custom authentication on top of Zyan.
Suppose you have a host with `NullAuthenticationProvider`.
`IPublicService` works as is, `ISecretService` needs authentication:

```csharp
public class SecretService: ISecretService
{
   private bool IsAuthenticated =>
       ServerSession.CurrentSession.SessionVariables
          .GetSessionVariable<bool>("IsAuthenticated");

   public void DoSecretStuff()
   {
      if (!IsAuthenticated)
          throw new SecurityException("SecretService requires authentication.");

      // do something authenticated
   }
}
```

Additional authentication could be done by a custom service like this (pseudocode):

```csharp
public interface IMySecretAuthenticator
{
     void Authenticate(string name, string password);
}

public class MySecretAuthenticator : IMySecretAuthenticator
{
    public void Authenticate(string name, string password)
    {
        // validate the user name and password
        if (name != "scott" || password != "tiger"))
        {
            throw new SecurityException("Invalid user name or password");
        }

        // store authentication data in the current session variables
        ServerSession.CurrentSession.SessionVariables["IsAuthenticated"] = true;
        ServerSession.CurrentSession.SessionVariables["UserName"] = name;
    }
}
```

When a client is connected, it's not authenticated.
It can only call public services:

```csharp
var connection = new ZyanConnection(url);
var publicService = connection.CreateProxy<IPublicService>();
publicService.DoPublicStuff(); // ok

var secretService = connection.CreateProxy<ISecretService>();
secretService.DoSecretStuff(); // throws an exception
```

When a client needs to access `ISecretServices`, it has to authenticate:

```csharp
var auth = connection.CreateProxy<IMySecretAuthenticator>();
auth.Authenticate("scott", "tiger");

// there is no need to recreate ISecretService proxy
secretService.DoSecretStuff(); // ok
```

Hope it helps.

**Comment by teleavtomatika** [comment]
Thank you very much for your extremely detailed answer. But i think your solution couldn't be used in our environment. Usually we calls such a things like crutches (Костыль по нашему ;-), perphaps you know.

We decided to add a separate ZyanHost with different TCP port for publicly available services. Anyway **thank you very much** for a spent time!

**Comment by yallie** [comment]
You're welcome!
