### ISSUE TITLE
Server-side connection bottleneck

### ISSUE THREAD

**Issue by teleavtomatika** [zyanfx/Zyan#66]
Hello Alexey!
We discovered unusual backend connection receiving bottleneck in some situation.

We have a host, on tcp port **[18 000]**, like this:

```
var port = 18000
var publicProtocol = new TcpDuplexServerProtocolSetup(port, new NullAuthenticationProvider(), true);
publicProtocol.CompressionMethod = ServiceClient.DefaultCompressionMethod;
publicProtocol.CompressionThreshold = ServiceClient.DefaultCompressionThreshold;
publicHost = new ZyanComponentHost("Public", publicProtocol);
```

And creating connection (on server side too) to other public backend server on port **[18 000 + 1]**, like this: 
```
var hostId = "Public";
var port = 18001;
var protocol = new TcpDuplexClientProtocolSetup(true);
protocol.CompressionMethod = Zyan.Communication.ChannelSinks.Compression.CompressionMethod.DeflateStream;
protocol.CompressionThreshold = 1300;
var connection = new ZyanConnection($"tcpex://{host}:{port}/{hostId}", protocol, null, true, true);
```

So bottleneck is produced like this: 

when we trying to connect on server side to other not responding server, connecting process hanging on `var connection = new ZyanConnection($"tcpex://{host}:{port}/{hostId}", protocol, null, true, true);` until timeout exception thrown. During this time no other clients can connect to any hosts hosted on server-side, even with different tcp port.

It looks very strange and unusual. Seems like some shared object, that used by host and client code, were locked during `ZyanConnection` establishing and prevent from serving new connections for hosts.

Any ideas?

**Comment by yallie** [comment]
Hi @teleavtomatika 

Sorry for my late response. That looks quite strange.
There is no shared lock held by the connection constructor, as far as I know.
But it may be related to tcpex channel specifics.
Does it reproduce on other channels such as non-duplex tcp?

**Comment by teleavtomatika** [comment]
Hi Allex, i've replaced TcpDuplexClientProtocolSetup with TcpCustomClientProtocolSetup and this solves the problem. 

Seems the problem is on TcpDuplexClientProtocolSetup side.

**Comment by yallie** [comment]
Great! Thanks for reporting your findings 👍
