### ISSUE TITLE
Please log on first

### ISSUE THREAD

**Issue by TonyValenti** [zyanfx/Zyan#68]
Sometimes I get this error after a component has been alive for a while:
Zyan.Communication.InvalidSessionException: 'Session ID '3e004070-197d-4b93-ac7a-84f30dc169db' is invalid. Please log on first.'

How do I make it not happen?

**Comment by yallie** [comment]
Hi Tony,

Zyan session manager sweeps sessions that seem to be inactive.
If your client doesn't call any remote methods, its session will eventually expire.
To make sure the session doesn't expire, ZyanConnection can send heartbeat events.
Once in a while your client will notify the server that it's still running.
This feature is enabled by setting `PollingEnabled` to true:

https://github.com/zyanfx/Zyan/blob/master/source/Zyan.Communication/ZyanConnection.cs#L788
