### ISSUE TITLE
Activaton-Type

### ISSUE THREAD

**Issue by csharpdeveloper12** [zyanfx/Zyan#7]
First, thanks for the Zyan-Component :)

Is it possible to create a proxy, wich creates in the server an class-instance that is singleton for the scope?

var proxy = zyanConnection.CreateProxy< IFunctions>();
proxy.Id = 1;

var proxy2 = zyanConnection.CreateProxy< IFunctions>();
proxy2.Id = 2;

var id1 = proxy.Id;
var id2 = proxy2.Id;

If i declare the registration as singleton the results are:
id1 = 2; id2 = 2

If i declare the registration as single-call the results are:
id1 = 0; id2 = 0

Now my question whether Zyan can be used for the behavior that the results are "id1 = 1" and "id2 = 2"?

Thanks in advance

**Comment by yallie** [comment]
Hello,

Zyan components are stateless, so you can't get this behavior within a single session.
But it's possible if proxy and proxy2 belong to different clients (or connections).
To emulate singleton-per-client behavior you can use session variables, i.e.

```c#
class SingletonPerClientExample
{
  public int Id
  {
    set { ServerSession.CurrentSession.SessionVariables["SingletonId"] = value; }
    get { return Convert.ToInt32(ServerSession.CurrentSession.SessionVariables["SingletonId"]); }
  }
}
```

Hope that helps.

**Comment by csharpdeveloper12** [comment]
Hello yallie,

thank you for the fast response and the example.

I try to implement it with session variables.

Tank you :)
