### ISSUE TITLE
[Question] Dotnet Core

### ISSUE THREAD

**Issue by batiati** [zyanfx/Zyan#78]
Hi,

I'm porting my app to .Net Core and I'm looking for a replacement for WCF, it seems that Zyan is perfect for this job, and with much less effort than converting all my services do gRPC.

Is there any considerations about the current support for .Net Core and future plans for Zyan supports .Net 5.0?

Thanks

**Comment by yallie** [comment]
Hi Rafael,

Unfortunately, .NET Code doesn't include the Remoting stack which is what Zyan is based upon.
Zyan works on desktop .NET framework, Mono and Xamarin, but not .NET Core. 

Regards, Alex

**Comment by batiati** [comment]
Thank you for replying!
It's a shame that Microsoft won't include a lot of enterprise-class features on .Net 5.0.

Regards
