### ISSUE TITLE
User determination in BasicWindowsAuthProvider

### ISSUE THREAD

**Issue by heikar** [zyanfx/Zyan#90]
Hi yallie,

I hope you are well :)

I have a small request for you:

- In a project, the user uses its email address for login. In the case of the `BasicWindowsAuthProvider` i need an entry point to check whether the user is enabled and to convert the given email address in the credentials to the mapped (AD) user name.
- Also the domain determination should happened on the server not in the credentials on client side.

Maybe you can made the `ValidateWindowsCredentials` Method virtual and make the username and domain parameter out/ref.
So it is possible to inherit the class and override this method, check whether the user is enabled and return the mapped user name in the parameter.

Many greetings
heikar

**Comment by yallie** [comment]
Hello @heikar,

Glad to hear from you.
I think, there's no problem to make it protected virtual.
It wouldn't be a breaking change because the method is currently private.

Would you mind creating a pull request with your changes?

**Comment by heikar** [comment]
Hello @yallie,

that sounds great :)

In the next days i will make a pull request with the changes and an example.

**Comment by heikar** [comment]
Hi @yallie ,
i have opened the follow pull request #91 .

Please check the changes :)

Many greetings
heikar
