### ISSUE TITLE
Custom serialization have to be configured for List<> too 

### ISSUE THREAD

**Issue by oleksabor** [zyanfx/Zyan#92]
Hi there

The custom serialization requires to be set for the certain type (interface) only. However it would be nice to have it working for `List<T>` or arrays `T[]`

It is a little bit surplus to write for each type something like 
```
repo.RegisterSerializationHandler(typeof(Sample), new CSerialization());
repo.RegisterSerializationHandler(typeof(List<Sample>), new CSerialization());
```
I know that it is possible to use interface (because of the `IsAssignableFrom` in the `FindMatchingSerializationHandler` implementation) but it won't work for `List<>` unfortunately, 
```
public class Data1 : ICustomSerialized
{}
public class Data1 : ICustomSerialized
{}
repo.RegisterSerializationHandler(typeof(ICustomSerialized), new CSerialization()); // both Data1 and Data2 are serialized with the CSerialization 
repo.RegisterSerializationHandler(typeof(List<????>), new CSerialization()); // but not List<Data1> List<Data2> or List<ICustomSerialized>
```

I'm thinking that `SerializationHandlerRepository.FindMatchingSerializationHandler` may be adjusted to get dto object type from `List<T>` or `T[]`

```
public void FindMatchingSerializationHandler(Type type, out Type handledType, out ISerializationHandler handler)
{
	if (type == null)
		throw new ArgumentNullException("type");

	handledType = null;
	handler = null;

	type = GetUnderlyingType(type);
....
}
/// <summary>
/// return underliyng type for lists and arrays
/// </summary>
/// <param name="type"></param>
/// <returns></returns>
public Type GetUnderlyingType(Type type)
{
	if (type.IsGenericType)
		return type.GetGenericArguments()[0];
	if (type.IsArray)
		return type.GetElementType();
	return type;
}
```
Does it have sense or I understand custom serialization in a wrong way?

Is it possible to set custom serializer for all objects btw (to replace binary serializer with the custom one)?

Regards

**Comment by yallie** [comment]
Hi @oleksabor, 

have you tried registering your handler for `IEnumerable<ICustomSerializable>`?
It should match both `List<Data1>` and `Data2[]`:

```csharp
public interface ICustomSerializable {}

public class Data1 : ICustomSerializable {}

public class Data2 : ICustomSerializable {}

static void Main()
{
	typeof(IEnumerable<ICustomSerializable>).IsAssignableFrom(typeof(Data1[])).Dump(); // true
	typeof(IEnumerable<ICustomSerializable>).IsAssignableFrom(typeof(List<Data2>)).Dump(); // true
	typeof(IEnumerable<ICustomSerializable>).IsAssignableFrom(typeof(IList<Data1>)).Dump(); // true
	typeof(IEnumerable<ICustomSerializable>).IsAssignableFrom(typeof(List<object>)).Dump(); // false
}
```

**Comment by yallie** [comment]
>I'm thinking that SerializationHandlerRepository.FindMatchingSerializationHandler may be adjusted to get dto object type from List<T> or T[]

I don't think it can be done automatically.

When you register a custom serialization handler for a type, you state that your handler can support that type. It doesn't always mean that a handler can process a `List<T>` of your type. So if the handler supports containers, you should specify that explicitly.

>Is it possible to set custom serializer for all objects btw (to replace binary serializer with the custom one)?

Well, not really.

You can probably register a custom serializer for `object` type, but RPC messages will be serialized by BinaryFormatter anyway. Serialization isn't fully customizable, it's only adjustable to a certain extent to handle types that aren't binary-serializable by design, like LINQ expressions.

**Comment by oleksabor** [comment]
registering handler for the `IEnumerable<ICustomSerializable>` works thank you very much.

I'm looking for the possibility to use `Ceras` serializer (instead of `BinaryFromatter`)  will continue with `RegisterSerializationHandler` .

Regards
